# DroneDetect V2 - Frequency Domain Exploration (V5)

## Motivation

**Why focus on frequency domain analysis?**

Swinney & Woods (2021) demonstrate in their paper ["The Effect of Real-World Interference on CNN Feature Extraction and Machine Learning Classification of Unmanned Aerial Systems"](https://www.mdpi.com/2226-4310/8/7/179) (Aerospace 2021, 8, 179) that:

> **"Overall, frequency domain features extracted from a CNN were shown to be more robust than time domain features in the presence of interference."**

**Quantitative results (Table from paper):**

| Representation | Detection (2 classes) | Type (8 classes) | Flight Mode (21 classes) |
|----------------|----------------------|------------------|-------------------------|
| PSD + LR | 100% | 98.1% (±0.4%) | 95.4% (±0.3%) |
| Spectrogram + LR | 96.7% | 90.5% | 87.3% |

**Conclusion:** Frequency domain features (PSD) are **7-8% more robust** to WiFi/Bluetooth interference.

**Additional confirmations:**
- [Swinney & Woods (2022)](https://www.mdpi.com/2226-4310/9/12/738): Low-cost Raspberry Pi implementation confirms PSD robustness
- [URSI 2024](https://www.ursi.org/proceedings/procAT24/papers/0475.pdf): "PSD has proven to be more reliable than simple spectrograms"
- [Glüge et al. (2023)](https://www.scitepress.org/Papers/2023/121768/121768.pdf): Independent confirmation of frequency domain advantage

---

> **Data scope:** This analysis uses **195 files** from **2 interference conditions** (CLEAN and BOTH) out of the full DroneDetect V2 dataset (390 files, 4 conditions). Training and evaluation notebooks (021-031) use the complete dataset.

This notebook focuses specifically on:
- **Power Spectral Density (PSD) analysis** using Welch's method
- Spectral signatures comparison across drone models
- Interference impact analysis

**Note**: Spectrograms (time-frequency representations) will be explored in a separate notebook dedicated to time-frequency analysis.

**Context**: RF signals from drones at 2.4 GHz (OcuSync, Lightbridge, WiFi) captured with BladeRF SDR.

## 1. Setup

In [1]:
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

import numpy as np
import pandas as pd
from pathlib import Path
import re

print("Setup complete!")

Setup complete!


In [2]:
from dronedetect import config, data_loader, preprocessing, features

In [3]:
SEGMENT_MS = 20
N_SEGMENTS_PER_FILE = 5
RANDOM_STATE = 42

NOTEBOOK_NAME = "003_exploration_frequentiel"
FIGURES_DIR = Path("./figures") / NOTEBOOK_NAME


def save_figure(fig, title: str):
    """
    Save plotly figure to PNG file.
    Filename is derived from the figure title.

    Args:
        fig: Plotly figure object
        title: Figure title (used for both display and filename)
    """
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    filename = re.sub(r'[^\w\s-]', '', title).strip()
    filename = re.sub(r'[\s-]+', '_', filename)
    filepath = FIGURES_DIR / f"{filename}.png"
    fig.write_image(str(filepath), width=1200, height=800)
    print(f"Saved: {filepath}")


def compute_psd_db(segment_norm, epsilon=1e-10):
    """
    Compute PSD and convert to dB scale.

    Args:
        segment_norm: Normalized IQ segment
        epsilon: Small value to avoid log(0). Default 1e-10 sets -100 dB noise floor.

    Returns:
        freqs: Frequency array (Hz)
        psd_db: PSD in dB scale
    """
    freqs, psd_linear = features.compute_psd(segment_norm)
    psd_db = 10 * np.log10(np.maximum(psd_linear, epsilon))
    return freqs, psd_db

In [4]:
if config.DATA_DIR.exists():
    df = data_loader.get_dataset_metadata(config.DATA_DIR)
    print(f"Total files: {len(df)}")
    print(f"Drones: {df['drone_code'].unique()}")
    print(f"States: {df['state'].unique()}")
    print(f"Interference: {df['interference'].unique()}")
else:
    df = None
    raise Exception("Dataset directory not found")

Total files: 195
Drones: ['MIN' 'INS' 'MAV' 'AIR' 'PHA' 'MA1' 'DIS']
States: ['HO' 'ON' 'FY']
Interference: ['CLEAN' 'BOTH']


## 2. Power Spectral Density Analysis

### PSD Parameters

| Parameter | Value | Justification |
|-----------|-------|---------------|
| **NFFT** | 1024 points | FFT length for Welch's method. Frequency resolution: FS/nfft = 58.6 kHz bins. |
| **Overlap** | 512 samples | 50% overlap for Welch's method (standard practice for variance reduction). |
| **Window** | Hamming | Reduces spectral leakage. Standard choice for PSD estimation with good side-lobe suppression. |
| **Noise floor percentile** | 10th percentile | **Arbitrary choice** for noise floor estimation (commonly used heuristic). |

**Reference**: Welch, P.D. (1967) - "The use of Fast Fourier Transform for the estimation of power spectra", IEEE Transactions on Audio and Electroacoustics, DOI: [10.1109/TAU.1967.1161901](https://doi.org/10.1109/TAU.1967.1161901)

### 2.1 Spectral Occupancy Validation (BW_99%)

Verify that the 60 MHz sampling rate preserves signal information.

**Criterion**: If BW_99% < 28 MHz (capture bandwidth), downsampling is safe.

In [5]:
from scipy.signal import welch

def compute_bw_99(iq_signal, fs, nperseg=4096):
    """Compute bandwidth containing 99% of signal energy."""
    freqs, psd = welch(iq_signal, fs=fs, nperseg=nperseg, return_onesided=False)
    freqs = np.fft.fftshift(freqs)
    psd = np.fft.fftshift(psd)

    psd_sorted_idx = np.argsort(psd)[::-1]
    psd_sorted = psd[psd_sorted_idx]
    cumsum = np.cumsum(psd_sorted) / np.sum(psd_sorted)
    n_bins_99 = np.searchsorted(cumsum, 0.99)

    freq_resolution = fs / nperseg
    bw_99_hz = n_bins_99 * freq_resolution

    return bw_99_hz / 1e6

bw_results = []
for drone in df['drone_code'].unique():
    files = df[(df['drone_code'] == drone) &
               (df['state'] == 'ON') &
               (df['interference'] == 'CLEAN')]['file_path']
    if len(files) == 0:
        files = df[df['drone_code'] == drone]['file_path']

    file_path = files.iloc[0]
    iq = data_loader.load_raw_iq(file_path)
    bw = compute_bw_99(iq[:int(config.FS)], config.FS)
    bw_results.append({'drone': drone, 'bw_99_mhz': bw})

bw_df = pd.DataFrame(bw_results).sort_values('bw_99_mhz', ascending=False)
print("BW_99% by drone (MHz):")
print(bw_df.to_string(index=False))

max_bw = bw_df['bw_99_mhz'].max()
print(f"\nMax BW_99%: {max_bw:.2f} MHz")
print(f"Capture BW: 28 MHz")
print(f"Downsampling safe: {'YES' if max_bw < 28 else 'NO - REVIEW NEEDED'}")

BW_99% by drone (MHz):
drone  bw_99_mhz
  AIR  24.873047
  MA1  22.778320
  INS  22.602539
  DIS  16.596680
  MAV  16.567383
  PHA  16.376953
  MIN   8.730469

Max BW_99%: 24.87 MHz
Capture BW: 28 MHz
Downsampling safe: YES


In [6]:
if config.DATA_DIR.exists() and df is not None:
    drones_to_plot = sorted(df['drone_code'].unique())

    fig = go.Figure()

    for drone in drones_to_plot:
        drone_files = df[(df['drone_code'] == drone) &
                         (df['state'] == 'ON') &
                         (df['interference'] == 'CLEAN')]

        if len(drone_files) > 0:
            file_path = Path(drone_files.iloc[0]['file_path'])
            iq = data_loader.load_raw_iq(file_path)

            segments = preprocessing.segment_signal(iq, segment_ms=SEGMENT_MS)
            segment_norm = preprocessing.normalize(segments[0])

            freqs, psd_db = compute_psd_db(segment_norm)

            fig.add_trace(go.Scatter(
                x=freqs / 1e6,
                y=psd_db,
                mode='lines',
                name=drone,
                line=dict(width=2)
            ))

    fig.update_layout(
        title="Spectral Signatures by Drone Model (CLEAN & ON mode)",
        xaxis_title="Frequency Offset (MHz)",
        yaxis_title="Power Spectral Density (dB)",
        height=600,
        hovermode='x unified'
    )
    save_figure(fig, "Spectral Signatures by Drone Model CLEAN ON dB")
    fig.show()

Saved: figures/003_exploration_frequentiel/Spectral_Signatures_by_Drone_Model_CLEAN_ON_dB.png


**Expected Output**

![Spectral Signatures by Drone Model — CLEAN/ON (dB)](./figures/003_exploration_frequentiel/Spectral_Signatures_by_Drone_Model_CLEAN_ON_dB.png)

Each drone exhibits a distinct spectral envelope. In this single-segment view, MA1 and MAV (both OcuSync) occupy different frequency offset regions despite similar power levels. MIN (WiFi) shows one of the narrower bandwidths, while AIR shows the broadest energy spread. MA1/MAV similarity is more apparent statistically across many segments (see Section 3) than in this single snapshot.

In [7]:
if config.DATA_DIR.exists() and df is not None:
    test_drones = ['AIR', 'MA1', 'MIN']
    interference_types = sorted(df['interference'].unique())

    fig = make_subplots(
        rows=len(test_drones), cols=1,
        subplot_titles=[f'{d}: {" vs ".join(interference_types)} Interference' for d in test_drones],
        vertical_spacing=0.08
    )

    palette = ['blue', 'red', 'green', 'orange', 'purple', 'brown']
    colors = {t: palette[i] for i, t in enumerate(interference_types)}

    for row_idx, drone in enumerate(test_drones, start=1):
        for interference in interference_types:
            drone_files = df[(df['drone_code'] == drone) &
                             (df['state'] == 'ON') &
                             (df['interference'] == interference)]

            if len(drone_files) > 0:
                file_path = Path(drone_files.iloc[0]['file_path'])
                iq = data_loader.load_raw_iq(file_path)

                segments = preprocessing.segment_signal(iq, segment_ms=SEGMENT_MS)
                segment_norm = preprocessing.normalize(segments[0])
                freqs, psd_db = compute_psd_db(segment_norm)

                fig.add_trace(
                    go.Scatter(
                        x=freqs / 1e6,
                        y=psd_db,
                        mode='lines',
                        name=interference if row_idx == 1 else None,
                        legendgroup=interference,
                        showlegend=(row_idx == 1),
                        line=dict(color=colors[interference], width=2)
                    ),
                    row=row_idx, col=1
                )

    condition_label = " vs ".join(interference_types)
    fig.update_xaxes(title_text="Frequency Offset (MHz)", row=len(test_drones), col=1)
    fig.update_yaxes(title_text="PSD (dB)")
    fig.update_layout(
        height=300 * len(test_drones),
        title_text=f"Interference Impact on Spectrum ({condition_label})",
        hovermode='x unified'
    )
    save_figure(fig, f"Interference Impact {condition_label}")
    fig.show()

Saved: figures/003_exploration_frequentiel/Interference_Impact_BOTH_vs_CLEAN.png


**Expected Output**

![Interference Impact — BOTH vs CLEAN](./figures/003_exploration_frequentiel/Interference_Impact_BOTH_vs_CLEAN.png)

The BOTH condition raises the noise floor across all frequencies due to WiFi/Bluetooth co-channel interference, but the main spectral peaks remain identifiable. Impact varies by drone protocol: AIR (OcuSync) with its broader bandwidth is most affected, while MIN (WiFi) with narrower spectrum is relatively less distorted.

## 3. Drone Discrimination Analysis (MA1/MAV)

MA1 (OcuSync 1.0) and MAV (OcuSync 2.0) share similar RF characteristics, making them the hardest pair to classify.

This section computes spectral statistics to quantify their separability:
- **Spectral kurtosis**: Peakedness of the power distribution across frequency bins
- **Spectral skewness**: Asymmetry of the power distribution
- **BW_90**: Number of frequency bins containing 90% of signal energy

**Caveat on Cohen's d**: Effect sizes reported below should be interpreted with caution. Sample sizes are small (N~10 per group), and the standard thresholds (small=0.2, medium=0.5, large=0.8) are calibrated for larger samples. With N~10, confidence intervals around d are wide.

In [8]:
from scipy.stats import kurtosis, skew

ma1_mav_features = []

for drone in ['MA1', 'MAV']:
    files = df[(df['drone_code'] == drone) &
               (df['interference'] == 'CLEAN')]['file_path'][:10]

    for file_path in files:
        iq = data_loader.load_raw_iq(file_path)
        segments = preprocessing.segment_signal(iq, segment_ms=SEGMENT_MS)
        seg_norm = preprocessing.normalize(segments[0])
        freqs, psd = features.compute_psd(seg_norm)

        psd_norm = psd / np.sum(psd)
        centroid = np.sum(freqs * psd_norm)
        psd_db = 10 * np.log10(np.maximum(psd, 1e-10))
        psd_sorted = np.sort(psd)[::-1]
        cumsum = np.cumsum(psd_sorted) / np.sum(psd_sorted)

        ma1_mav_features.append({
            'drone': drone,
            'kurtosis': kurtosis(psd_db),
            'skewness': skew(psd_db),
            'bw_90_bins': np.searchsorted(cumsum, 0.9),
            'spread_mhz': np.sqrt(np.sum((freqs - centroid)**2 * psd_norm)) / 1e6
        })

ma1_mav_df = pd.DataFrame(ma1_mav_features)

results = []
for col in ['kurtosis', 'skewness', 'bw_90_bins', 'spread_mhz']:
    ma1 = ma1_mav_df[ma1_mav_df['drone'] == 'MA1'][col]
    mav = ma1_mav_df[ma1_mav_df['drone'] == 'MAV'][col]
    pooled_std = np.sqrt((ma1.std()**2 + mav.std()**2) / 2)
    d = abs(ma1.mean() - mav.mean()) / pooled_std if pooled_std > 0 else 0
    results.append({'feature': col, 'MA1_mean': ma1.mean(), 'MAV_mean': mav.mean(), 'cohens_d': d})

results_df = pd.DataFrame(results)
print("=== MA1 vs MAV: Cohen's d (N~10 per group) ===")
print(results_df.to_string(index=False))
print("\nKurtosis (d=1.31) and skewness (d=1.45) show large effect sizes,")
print("but with N~10 per group, confidence intervals are wide.")
print("Standard spectral statistics alone are insufficient to reliably separate MA1 from MAV.")

fig = make_subplots(rows=2, cols=2, subplot_titles=['Kurtosis', 'Skewness', 'BW_90 (bins)', 'Spread (MHz)'])
for i, col in enumerate(['kurtosis', 'skewness', 'bw_90_bins', 'spread_mhz']):
    row, col_idx = i // 2 + 1, i % 2 + 1
    for drone, color in [('MA1', 'blue'), ('MAV', 'red')]:
        vals = ma1_mav_df[ma1_mav_df['drone'] == drone][col]
        fig.add_trace(go.Box(y=vals, name=drone, marker_color=color, showlegend=(i==0)),
                      row=row, col=col_idx)
fig.update_layout(height=600, title="MA1 vs MAV Spectral Feature Comparison")
save_figure(fig, "ma1_mav_discrimination_features")
fig.show()

=== MA1 vs MAV: Cohen's d (N~10 per group) ===
   feature  MA1_mean   MAV_mean  cohens_d
  kurtosis  3.323109   7.626951  1.309411
  skewness  2.071830   2.852752  1.454876
bw_90_bins 86.600000 180.200000  0.632970
spread_mhz  7.946051   8.319868  0.121344

Kurtosis (d=1.31) and skewness (d=1.45) show large effect sizes,
but with N~10 per group, confidence intervals are wide.
Standard spectral statistics alone are insufficient to reliably separate MA1 from MAV.
Saved: figures/003_exploration_frequentiel/ma1_mav_discrimination_features.png


**Expected Output**

![MA1 vs MAV Discrimination Features](./figures/003_exploration_frequentiel/ma1_mav_discrimination_features.png)

Kurtosis (d=1.31) and skewness (d=1.45) show large Cohen's d effect sizes between MA1 and MAV, indicating measurable spectral shape differences. BW_90 shows moderate separation (d=0.63) while spectral spread is nearly identical (d=0.12), confirming scalar statistics alone are insufficient — CNN feature extraction is needed.